import type { SupportedLanguage } from "@open-party-lab/game-core";
import type { BlickwinkelRound } from "./protocol.js";

type QuestionRow = readonly [string, string, string];

const rows: readonly QuestionRow[] = [
  ["Alltag", "Wer würde am ehesten den eigenen Geburtstag vergessen?", "Who is most likely to forget their own birthday?"],
  ["Alltag", "Wer kommt am ehesten mit einem völlig unnötigen, aber großartigen Gadget nach Hause?", "Who is most likely to come home with a completely unnecessary but brilliant gadget?"],
  ["Alltag", "Wen würdet ihr anrufen, wenn ihr spontan Hilfe beim Umzug braucht?", "Who would you call for last-minute help moving house?"],
  ["Alltag", "Wer führt die längste Diskussion mit einem Navi?", "Who would have the longest argument with a navigation app?"],
  ["Alltag", "Wer hat am ehesten einen geheimen Vorrat an Snacks?", "Who is most likely to have a secret snack stash?"],
  ["Alltag", "Wer würde einen freien Nachmittag am besten verplanen?", "Who would be best at filling an unexpectedly free afternoon?"],
  ["Alltag", "Wer macht aus einer kleinen Besorgung einen halben Tagesausflug?", "Who turns a quick errand into a half-day adventure?"],
  ["Alltag", "Wer findet in einer fremden Stadt zuerst den besten Kaffee?", "Who would find the best coffee first in a new city?"],
  ["Reisen", "Mit wem würdet ihr am liebsten eine Woche ohne festen Plan verreisen?", "Who would you most like to take on a week-long trip with no fixed plan?"],
  ["Reisen", "Wer packt für ein Wochenende, als würde es einen Monat dauern?", "Who packs for a weekend as if it lasted a month?"],
  ["Reisen", "Wer würde sich auf einer Wanderung am ehesten mit einer Ziege anfreunden?", "Who is most likely to befriend a goat on a hike?"],
  ["Reisen", "Wer würde sich trauen, im Urlaub einen völlig neuen Sport auszuprobieren?", "Who would dare to try a completely new sport on holiday?"],
  ["Reisen", "Wer entdeckt auf Reisen die schönste Abkürzung – oder den längsten Umweg?", "Who finds the best shortcut—or the longest detour—while travelling?"],
  ["Reisen", "Wer könnte sich am ehesten mit Händen und Füßen verständigen?", "Who could get by best using only gestures?"],
  ["Kreativ", "Wer würde aus drei Kartons ein erstaunliches Kostüm bauen?", "Who could make an amazing costume out of three cardboard boxes?"],
  ["Kreativ", "Wer sollte für die Gruppe einen neuen Feiertag erfinden?", "Who should invent a new holiday for the group?"],
  ["Kreativ", "Wessen spontane Geschichte würde am ehesten als Film enden?", "Whose made-up story is most likely to become a movie?"],
  ["Kreativ", "Wer hat vermutlich ein Talent, von dem hier noch niemand weiß?", "Who probably has a talent nobody here knows about yet?"],
  ["Kreativ", "Wer könnte einen langweiligen Gegenstand am besten verkaufen?", "Who could do the best job selling a boring object?"],
  ["Kreativ", "Wer würde eine Band gründen, bevor der Name feststeht?", "Who would start a band before deciding on its name?"],
  ["Abenteuer", "Wen würdet ihr als Erstes in ein Escape Room Team wählen?", "Who would you pick first for an escape room team?"],
  ["Abenteuer", "Wer bleibt am ruhigsten, wenn plötzlich alle Pläne platzen?", "Who stays calmest when every plan suddenly falls apart?"],
  ["Abenteuer", "Wer würde einer geheimnisvollen Einladung am ehesten folgen?", "Who would be most likely to follow a mysterious invitation?"],
  ["Abenteuer", "Wer würde bei einer Schatzsuche zuerst die richtige Spur entdecken?", "Who would spot the right clue first on a treasure hunt?"],
  ["Abenteuer", "Wer könnte einen Regentag am besten in ein Abenteuer verwandeln?", "Who could turn a rainy day into an adventure best?"],
  ["Abenteuer", "Wen wollt ihr bei einer spontanen Karaoke-Runde im Team haben?", "Who would you want on your team at spontaneous karaoke?"],
  ["Freundschaft", "Wer merkt als Erstes, wenn es jemandem nicht gut geht?", "Who notices first when someone is having a rough day?"],
  ["Freundschaft", "Wer kann am besten einen Streit mit einem einzigen Satz beenden?", "Who can end an argument with a single sentence?"],
  ["Freundschaft", "Wer erinnert sich an die kleinsten Details aus euren Gesprächen?", "Who remembers the smallest details from your conversations?"],
  ["Freundschaft", "Wer würde ein Geschenk aussuchen, das genau ins Schwarze trifft?", "Who would choose a gift that hits exactly the right note?"],
  ["Freundschaft", "Wen würdet ihr als geheimen Berater für eine schwierige Entscheidung wählen?", "Who would you choose as a secret adviser for a tough decision?"],
  ["Freundschaft", "Wer bringt eine Gruppe am schnellsten zum Lachen?", "Who gets a group laughing the fastest?"],
  ["Party", "Wer würde auf einer Feier zuerst mit allen Gästen gesprochen haben?", "Who would have spoken to every guest first at a party?"],
  ["Party", "Wer startet am ehesten eine Tanzfläche, obwohl keine Musik läuft?", "Who is most likely to start a dance floor before any music plays?"],
  ["Party", "Wer würde bei einem Quiz den überraschendsten Spezialbereich kennen?", "Who would know the most surprising niche facts in a quiz?"],
  ["Party", "Wen wollt ihr als Mitbewohner für ein Haus voller Haustiere?", "Who would you choose as a housemate in a home full of pets?"],
  ["Party", "Wer würde sich am ehesten an den Namen eines Hundes erinnern, aber nicht an den seines Menschen?", "Who would remember a dog's name but not its human's?"],
  ["Zukunft", "Wer wird am ehesten eine neue Leidenschaft entdecken und sofort alle anstecken?", "Who is most likely to discover a new passion and get everyone into it?"],
  ["Zukunft", "Wer hätte den besten kleinen Laden in einer Nebenstraße?", "Who would run the best little shop on a side street?"],
  ["Zukunft", "Wer würde in zehn Jahren noch dieselbe Lieblingsgeschichte erzählen?", "Who will still be telling the same favourite story in ten years?"],
  ["Zukunft", "Wer hat am ehesten eine Überraschung geplant, von der niemand etwas ahnt?", "Who is most likely to have a surprise planned that nobody suspects?"],
  ["Zukunft", "Wer würde aus einem Hobby am ehesten einen Beruf machen?", "Who is most likely to turn a hobby into a job?"],
  ["Zukunft", "Mit wem würdet ihr gern gemeinsam ein Café eröffnen?", "Who would you like to open a café with?"],
  ["Fantasie", "Wer wäre die beste Person, falls die Gruppe plötzlich schrumpft?", "Who would be the best person if the whole group suddenly shrank?"],
  ["Fantasie", "Wer würde mit einem Drachen eher verhandeln als weglaufen?", "Who would negotiate with a dragon instead of running away?"],
  ["Fantasie", "Wer wäre auf einer Raumstation am besten für die Pflanzen zuständig?", "Who would be best at looking after plants on a space station?"],
  ["Fantasie", "Wer könnte eine Insel mit nur drei Gegenständen am besten einrichten?", "Who could best set up an island with only three objects?"],
  ["Fantasie", "Wer würde ein Haustier wählen, das sonst niemand wählen würde?", "Who would pick a pet nobody else would choose?"],
  ["Fantasie", "Wessen Leben sollte verfilmt werden – als Komödie?", "Whose life should be made into a comedy film?"],
  ["Fantasie", "Wer könnte eine Geistervilla am gemütlichsten machen?", "Who could make a haunted house feel the cosiest?"],
  ["Fantasie", "Wer würde aus Versehen in einer völlig anderen Zeit landen und sich dort zurechtfinden?", "Who would accidentally end up in another era and find their feet there?"],
  ["Fantasie", "Wen würdet ihr zum Kapitän eines sehr chaotischen Piratenschiffs wählen?", "Who would you pick as captain of a very chaotic pirate ship?"],
  ["Alltag", "Wer könnte am überzeugendsten so tun, als hätte er den Film schon gesehen?", "Who could most convincingly pretend to have seen the movie?"],
  ["Reisen", "Wer findet am ehesten den besten Platz für ein Picknick?", "Who is most likely to find the perfect picnic spot?"],
  ["Kreativ", "Wer könnte aus einem Versprecher einen neuen Spruch machen?", "Who could turn a slip of the tongue into a new catchphrase?"],
  ["Freundschaft", "Wer würde für einen Freund am spontansten eine Stunde Zug fahren?", "Who would most spontaneously take a one-hour train ride for a friend?"],
  ["Party", "Wer wäre bei einer Kostümparty am schwersten zu erkennen?", "Who would be hardest to recognise at a costume party?"],
  ["Zukunft", "Wer könnte später eine sehr ungewöhnliche Sammlung besitzen?", "Who might end up with a very unusual collection?"],
  ["Fantasie", "Wer könnte einen Roboter am besten davon überzeugen, Urlaub zu machen?", "Who could best convince a robot to take a holiday?"],
  ["Abenteuer", "Wer würde den längsten Weg nehmen, nur weil die Aussicht besser ist?", "Who would take the longer route just for a better view?"],
  ["Freundschaft", "Wer macht aus einem normalen Abend eine Erinnerung, die bleibt?", "Who turns an ordinary evening into a lasting memory?"],
  ["Kreativ", "Wer würde für ein Brettspiel die besten Hausregeln erfinden?", "Who would invent the best house rules for a board game?"],
  ["Alltag", "Wer würde eine Pflanze am längsten am Leben halten?", "Who would keep a plant alive the longest?"],
  ["Party", "Wer könnte einen völlig falschen Text mit größtem Selbstvertrauen mitsingen?", "Who could sing completely wrong lyrics with total confidence?"],
  ["Fantasie", "Wer wäre als Bürgermeister eines Dorfes aus Katzen am überzeugendsten?", "Who would be the most convincing mayor of a town full of cats?"],
  ["Zukunft", "Wer würde am ehesten ein Buch über die Gruppe schreiben?", "Who is most likely to write a book about this group?"],
  ["Abenteuer", "Wer würde bei einem Stromausfall zuerst eine gute Idee haben?", "Who would have the first good idea during a power cut?"],
  ["Freundschaft", "Wer könnte zwei Menschen vorstellen, die danach unzertrennlich werden?", "Who could introduce two people who would become inseparable?"],
  ["Reisen", "Wer würde im Urlaub am ehesten einen geheimen Lieblingsort entdecken?", "Who would discover a secret favourite spot on holiday?"],
  ["Alltag", "Wer könnte am längsten ohne Handy auskommen?", "Who could go the longest without a phone?"],
  ["Kreativ", "Wessen selbst erfundener Feiertag würde allen gefallen?", "Whose invented holiday would everyone enjoy?"],
  ["Fantasie", "Wer wäre am besten darin, einem Außerirdischen die Erde zu erklären?", "Who would be best at explaining Earth to an alien?"],
  ["Zukunft", "Wer würde am ehesten mit einer ganz neuen Sportart berühmt werden?", "Who is most likely to become famous for inventing a new sport?"],
  ["Party", "Wer würde einen Spieleabend so gut organisieren, dass niemand nach Hause will?", "Who could organise a game night so well nobody wants to leave?"],
  ["Abenteuer", "Wer vertraut bei einer Weggabelung am ehesten dem Bauchgefühl?", "Who would trust their gut at a fork in the road?"],
  ["Freundschaft", "Wer würde den besten Mutmach-Brief schreiben?", "Who would write the best encouraging note?"],
  ["Alltag", "Wer kann am besten aus Resten ein richtiges Essen machen?", "Who can make a proper meal from leftovers best?"],
  ["Fantasie", "Wer würde bei einer Zeitreise als Erstes ein Souvenir mitbringen?", "Who would bring back a souvenir first after time travelling?"],
  ["Reisen", "Wer könnte am besten einen fremden Ort ohne Karte erkunden?", "Who could explore an unfamiliar place without a map best?"],
  ["Kreativ", "Wer würde einem ganz normalen Gegenstand einen Namen geben?", "Who would give a perfectly ordinary object a name?"],
  ["Zukunft", "Wessen Idee könnte eines Tages überraschend nützlich sein?", "Whose idea might unexpectedly come in handy one day?"]
];

export function getBlickwinkelQuestions(language: SupportedLanguage): BlickwinkelRound[] {
  return rows.map(([category, de, en], index) => ({
    id: `blickwinkel-${index + 1}`,
    kind: "pick",
    category,
    prompt: language === "en" ? en : de
  }));
}
